version: '3.8'
services:
  db:
    image: postgres:16
    container_name: litellm_db
    restart: always
    environment:
      POSTGRES_USER: ${LITELLM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LITELLM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LITELLM_POSTGRES_DATABASE}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - "network"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - "network"
  
  
  litellm:
    container_name: litellm-proxy
    image: ghcr.io/berriai/litellm:main-v1.40.7.dev1
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./config.yml:/app/config.yaml
    depends_on:
      - db
      - ollama
    env_file:
      - .env
    networks:
      - "network"
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8", "--detailed_debug" ]

networks:
  network:
   external:
    name: appliance
    
volumes:
  data:
    name: litellm-pgdata
